/* eslint-disable import/no-extraneous-dependencies */
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import eslint from 'vite-plugin-eslint';
import dts from 'vite-plugin-dts';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [dts({ rollupTypes: true }), react(), eslint()],
  build: {
    cssCodeSplit: false,
    lib: {
      entry: 'src/index.ts',
      name: 'index',
      fileName: 'index',
    },
    rollupOptions: {
      // Externalize deps that shouldn't be bundled into the library.
      external: [
        'antd',
        'd3-array',
        'd3-delaunay',
        'd3-format',
        'd3-geo',
        'd3-hierarchy',
        'd3-scale',
        'd3-selection',
        'd3-shape',
        'd3-zoom',
        'date-fns',
        'dom-to-image',
        'file-saver',
        'lodash.flattendeep',
        'lodash.max',
        'lodash.maxby',
        'lodash.min',
        'lodash.minby',
        'lodash.orderby',
        'lodash.reverse',
        'lodash.sortby',
        'lodash.sum',
        'lodash.sumby',
        'lodash.uniqby',
        'lodash.uniq',
        'lucide-react',
        'maplibre-gl',
        'pmtiles',
        'react',
        'react-csv',
        'react-dom',
        'simple-statistics',
        'styled-components',
        'undp-viz-colors',
        'xlsx',
      ],
      output: {
        globals: {
          antd: 'antd',
          'd3-array': 'd3',
          'd3-delaunay': 'd3',
          'd3-format': 'd3',
          'd3-geo': 'd3',
          'd3-hierarchy': 'd3',
          'd3-scale': 'd3',
          'd3-selection': 'd3',
          'd3-shape': 'd3',
          'd3-zoom': 'd3',
          'date-fns': 'dateFns',
          'dom-to-image': 'domtoimage',
          'file-saver': 'saveAs',
          'lodash.flattendeep': '_',
          'lodash.max': '_',
          'lodash.maxby': '_',
          'lodash.min': '_',
          'lodash.minby': '_',
          'lodash.orderby': '_',
          'lodash.reverse': '_',
          'lodash.sortby': '_',
          'lodash.sum': '_',
          'lodash.sumby': '_',
          'lodash.uniqby': '_',
          'lodash.uniq': '_',
          'lucide-react': 'lucideReact',
          'maplibre-gl': 'maplibreGl',
          pmtiles: 'pmtiles',
          react: 'React',
          'react-csv': 'ReactCSV',
          'react-dom': 'ReactDOM',
          'simple-statistics': 'ss',
          'styled-components': 'styled',
          'undp-viz-colors': 'UNDPColorModule',
          xlsx: 'XLSX',
        },
      },
    },
    sourcemap: true,
    emptyOutDir: true,
  },
  server: {
    cors: {
      origin: '*',
      methods: ['GET'],
      preflightContinue: false,
      optionsSuccessStatus: 204,
    },
  },
});
