export const GraphList = [
  {
    graphName: 'Horizontal bar graph',
    graphID: 'horizontalBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Horizontal stacked bar graph',
    graphID: 'horizontalStackedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Horizontal grouped bar graph',
    graphID: 'horizontalGroupedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Vertical bar graph',
    graphID: 'verticalBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Vertical stacked bar graph',
    graphID: 'verticalStackedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Vertical grouped bar graph',
    graphID: 'verticalGroupedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated horizontal bar chart',
    graphID: 'animatedHorizontalBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated horizontal stacked bar chart',
    graphID: 'animatedHorizontalStackedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated horizontal grouped bar chart',
    graphID: 'animatedHorizontalGroupedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated vertical bar chart',
    graphID: 'animatedVerticalBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated vertical stacked bar chart',
    graphID: 'animatedVerticalStackedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated vertical grouped bar chart',
    graphID: 'animatedVerticalGroupedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Horizontal bee swarm chart',
    graphID: 'horizontalBeeSwarmChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Vertical bee swarm chart',
    graphID: 'verticalBeeSwarmChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Butterfly chart',
    graphID: 'butterflyChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated butterfly chart',
    graphID: 'animatedButterflyChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Circle packing',
    graphID: 'circlePacking',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Data table',
    graphID: 'dataTable',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Pie/donut chart',
    graphID: 'donutChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Horizontal dumbbell chart',
    graphID: 'horizontalDumbbellChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Vertical dumbbell chart',
    graphID: 'verticalDumbbellChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated horizontal dumbbell chart',
    graphID: 'animatedHorizontalDumbbellChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated vertical dumbbell chart',
    graphID: 'animatedVerticalDumbbellChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Heat map',
    graphID: 'heatMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Histogram',
    graphID: 'histogram',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Line chart',
    graphID: 'lineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Multi-line chart',
    graphID: 'multiLineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Difference line chart',
    graphID: 'differenceLineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Dual-axes line chart',
    graphID: 'dualAxisLineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Spark line',
    graphID: 'sparkLine',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Choropleth map',
    graphID: 'choroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Bi-variate choropleth map',
    graphID: 'biVariateChoroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Dot density map',
    graphID: 'dotDensityMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated choropleth map',
    graphID: 'animatedChoroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated bi-variate choropleth map',
    graphID: 'animatedBiVariateChoroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated dot density map',
    graphID: 'animatedDotDensityMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'GeoHub map with comparison',
    graphID: 'geoHubCompareMap',
    availableInGriddedGraph: false,
    geoHubMapPresentation: true,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'GeoHub map',
    graphID: 'geoHubMap',
    availableInGriddedGraph: false,
    geoHubMapPresentation: true,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'GeoHub map with layer selection',
    graphID: 'geoHubMapWithLayerSelection',
    availableInGriddedGraph: false,
    geoHubMapPresentation: true,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Pareto chart',
    graphID: 'paretoChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Scatter plot',
    graphID: 'scatterPlot',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated scatter plot',
    graphID: 'animatedScatterPlot',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Slope chart',
    graphID: 'slopeChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Stacked area chart/area chart',
    graphID: 'stackedAreaChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Statistic card',
    graphID: 'statCard',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Horizontal strip chart',
    graphID: 'horizontalStripChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Vertical strip chart',
    graphID: 'verticalStripChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Tree map',
    graphID: 'treeMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Unit chart',
    graphID: 'unitChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Sankey chart',
    graphID: 'sankeyChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
];
