export const GraphList = [
  {
    graphName: 'Bar graph',
    graphID: 'barChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Stacked bar graph',
    graphID: 'stackedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Grouped bar graph',
    graphID: 'groupedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated bar chart',
    graphID: 'animatedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated stacked bar chart',
    graphID: 'animatedStackedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated grouped bar chart',
    graphID: 'animatedGroupedBarChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Bee swarm chart',
    graphID: 'beeSwarmChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Butterfly chart',
    graphID: 'butterflyChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated butterfly chart',
    graphID: 'animatedButterflyChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Circle packing',
    graphID: 'circlePacking',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Data table',
    graphID: 'dataTable',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Pie/donut chart',
    graphID: 'donutChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Dumbbell chart',
    graphID: 'dumbbellChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated dumbbell chart',
    graphID: 'animatedDumbbellChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Heat map',
    graphID: 'heatMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Histogram',
    graphID: 'histogram',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Line chart',
    graphID: 'lineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Multi-line chart',
    graphID: 'multiLineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Difference line chart',
    graphID: 'differenceLineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Dual-axes line chart',
    graphID: 'dualAxisLineChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Line chart with interval',
    graphID: 'lineChartWithConfidenceInterval',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Spark line',
    graphID: 'sparkLine',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Choropleth map',
    graphID: 'choroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Bi-variate choropleth map',
    graphID: 'biVariateChoroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Dot density map',
    graphID: 'dotDensityMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated choropleth map',
    graphID: 'animatedChoroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated bi-variate choropleth map',
    graphID: 'animatedBiVariateChoroplethMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated dot density map',
    graphID: 'animatedDotDensityMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'GeoHub map with comparison',
    graphID: 'geoHubCompareMap',
    availableInGriddedGraph: false,
    geoHubMapPresentation: true,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'GeoHub map',
    graphID: 'geoHubMap',
    availableInGriddedGraph: false,
    geoHubMapPresentation: true,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'GeoHub map with layer selection',
    graphID: 'geoHubMapWithLayerSelection',
    availableInGriddedGraph: false,
    geoHubMapPresentation: true,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Pareto chart',
    graphID: 'paretoChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Scatter plot',
    graphID: 'scatterPlot',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Animated scatter plot',
    graphID: 'animatedScatterPlot',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Slope chart',
    graphID: 'slopeChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Stacked area chart/area chart',
    graphID: 'stackedAreaChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Statistic card',
    graphID: 'statCard',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Strip chart',
    graphID: 'stripChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Tree map',
    graphID: 'treeMap',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Unit chart',
    graphID: 'unitChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: true,
  },
  {
    graphName: 'Sankey chart',
    graphID: 'sankeyChart',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
  {
    graphName: 'Data cards list',
    graphID: 'dataCards',
    availableInGriddedGraph: true,
    geoHubMapPresentation: false,
    availableInWideToLongFormat: false,
  },
];
