import { P } from '@undp/design-system-react';

import { AnimatedButterflyChart } from '../Graphs/ButterflyChart/Animated';
import { ButterflyChart } from '../Graphs/ButterflyChart/Simple';
import { CirclePackingGraph } from '../Graphs/CirclePackingGraph';
import { DataTable } from '../Graphs/DataTable';
import { DonutChart } from '../Graphs/DonutChart';
import { HeatMap } from '../Graphs/HeatMap';
import { Histogram } from '../Graphs/Histogram';
import { DualAxisLineChart } from '../Graphs/LineCharts/DualAxisLineChart';
import { SimpleLineChart } from '../Graphs/LineCharts/LineChart';
import { MultiLineChart } from '../Graphs/LineCharts/MultiLineChart';
import { SparkLine } from '../Graphs/LineCharts/SparkLine';
import { AnimatedBiVariateChoroplethMap } from '../Graphs/Maps/BiVariateMap/Animated';
import { BiVariateChoroplethMap } from '../Graphs/Maps/BiVariateMap/Simple';
import { AnimatedChoroplethMap } from '../Graphs/Maps/ChoroplethMap/Animated';
import { ChoroplethMap } from '../Graphs/Maps/ChoroplethMap/Simple';
import { AnimatedDotDensityMap } from '../Graphs/Maps/DotDensityMap/Animated';
import { DotDensityMap } from '../Graphs/Maps/DotDensityMap/Simple';
import { GeoHubCompareMaps } from '../Graphs/Maps/GeoHubMaps/CompareMaps';
import { GeoHubMap } from '../Graphs/Maps/GeoHubMaps/SimpleMap';
import { ParetoChart } from '../Graphs/ParetoChart';
import { AnimatedScatterPlot } from '../Graphs/ScatterPlot/Animated';
import { ScatterPlot } from '../Graphs/ScatterPlot/Simple';
import { SlopeChart } from '../Graphs/SlopeChart';
import { AreaChart } from '../Graphs/StackedAreaChart';
import { StatCardFromData } from '../Graphs/StatCard/StatCardFromData';
import { TreeMapGraph } from '../Graphs/TreeMapGraph';
import { UnitChart } from '../Graphs/UnitChart';
import { DifferenceLineChart } from '../Graphs/LineCharts/DifferenceLineChart';
import { GeoHubMapWithLayerSelection } from '../Graphs/Maps/GeoHubMaps/MapWithLayerSelection';
import { SankeyChart } from '../Graphs/SankeyChart';
import { LineChartWithConfidenceInterval } from '../Graphs/LineCharts/LineChartWithConfidenceInterval';
import { DataCards } from '../Graphs/DataCards';
import {
  SimpleBarGraph,
  GroupedBarGraph,
  StackedBarGraph,
} from '../Graphs/BarGraph';
import { DumbbellChart } from '../Graphs/DumbbellChart';
import { AnimatedDumbbellChart } from '../Graphs/DumbbellChart/Animated';
import {
  AnimatedBarGraph,
  AnimatedGroupedBarGraph,
  AnimatedStackedBarGraph,
} from '../Graphs/BarGraph/Animated';
import { StripChart } from '../Graphs/StripChart';
import { BeeSwarmChart } from '../Graphs/BeeSwarmChart';

import { getValues } from '@/Utils/getValues';
import {
  validateDataSchema,
  validateSettingsSchema,
} from '@/Utils/validateSchema';
import {
  DataTableColumnDataType,
  GraphConfigurationDataType,
  GraphSettingsDataType,
  GraphType,
  HighlightAreaSettingsDataType,
  HighlightAreaSettingsForScatterPlotDataType,
} from '@/Types';

interface Props {
  graph: GraphType;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  graphData: any;
  settings?: GraphSettingsDataType;
  debugMode?: boolean;
  graphDataConfiguration?: GraphConfigurationDataType[];
  readableHeader: {
    value: string;
    label: string;
  }[];
  updateFilters?: (_d: string) => void;
}

function GraphEl(props: Props) {
  const {
    settings,
    graph,
    graphData,
    debugMode,
    graphDataConfiguration,
    readableHeader,
    updateFilters,
  } = props;
  if (debugMode) {
    // eslint-disable-next-line no-console
    console.log(`Graph: ${graph}`);
    // eslint-disable-next-line no-console
    console.log('Transformed data:', graphData);
    // eslint-disable-next-line no-console
    console.log('Settings:', settings);
  }
  if (typeof graphData === 'string')
    return (
      <div
        className={`flex my-0 mx-auto grow flex-col justify-center ${
          settings?.width ? 'w-fit' : 'w-full'
        }`}
        style={{ height: 'inherit' }}
      >
        <P
          size='sm'
          marginBottom='none'
          className='p-2 text-center text-accent-dark-red dark:text-accent-red'
        >
          {graphData}
        </P>
      </div>
    );
  const graphComponents: Record<GraphType, React.ElementType | null> = {
    barChart: SimpleBarGraph,
    groupedBarChart: GroupedBarGraph,
    stackedBarChart: StackedBarGraph,
    lineChart: SimpleLineChart,
    dualAxisLineChart: DualAxisLineChart,
    multiLineChart: MultiLineChart,
    stackedAreaChart: AreaChart,
    choroplethMap: ChoroplethMap,
    biVariateChoroplethMap: BiVariateChoroplethMap,
    dotDensityMap: DotDensityMap,
    donutChart: DonutChart,
    slopeChart: SlopeChart,
    scatterPlot: ScatterPlot,
    dumbbellChart: DumbbellChart,
    treeMap: TreeMapGraph,
    circlePacking: CirclePackingGraph,
    heatMap: HeatMap,
    stripChart: StripChart,
    beeSwarmChart: BeeSwarmChart,
    butterflyChart: ButterflyChart,
    histogram: Histogram,
    sparkLine: SparkLine,
    paretoChart: ParetoChart,
    dataTable: DataTable,
    statCard: StatCardFromData,
    geoHubCompareMap: GeoHubCompareMaps,
    geoHubMap: GeoHubMap,
    unitChart: UnitChart,
    animatedScatterPlot: AnimatedScatterPlot,
    animatedBarChart: AnimatedBarGraph,
    animatedStackedBarChart: AnimatedStackedBarGraph,
    animatedGroupedBarChart: AnimatedGroupedBarGraph,
    animatedChoroplethMap: AnimatedChoroplethMap,
    animatedBiVariateChoroplethMap: AnimatedBiVariateChoroplethMap,
    animatedDotDensityMap: AnimatedDotDensityMap,
    animatedDumbbellChart: AnimatedDumbbellChart,
    animatedButterflyChart: AnimatedButterflyChart,
    differenceLineChart: DifferenceLineChart,
    geoHubMapWithLayerSelection: GeoHubMapWithLayerSelection,
    sankeyChart: SankeyChart,
    lineChartWithConfidenceInterval: LineChartWithConfidenceInterval,
    dataCards: DataCards,
  };
  const getGraphProps = (graphType: GraphType) => {
    switch (graphType) {
      case 'barChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          data: graphData,
          colors: settings?.colors as string | string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          height: settings?.height,
          width: settings?.width,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showValues: settings?.showValues,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          truncateBy: settings?.truncateBy,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          showLabels: settings?.showLabels,
          showColorScale: settings?.showColorScale,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          labelOrder: settings?.labelOrder,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          highlightedDataPoints: settings?.highlightedDataPoints,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          sortData: settings?.sortData,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          maxBarThickness: settings?.maxBarThickness,
          minBarThickness: settings?.minBarThickness,
          maxNumberOfBars: settings?.maxNumberOfBars,
          ariaLabel: settings?.ariaLabel,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          onSeriesMouseClick: (el: any) => {
            updateFilters?.(el.label);
          },
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          detailsOnClick: settings?.detailsOnClick,
          barAxisTitle: settings?.barAxisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'groupedBarChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showTicks: settings?.showTicks,
          truncateBy: settings?.truncateBy,
          colorDomain:
            settings?.colorDomain ||
            (getValues(
              'size',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          colorLegendTitle: settings?.colorLegendTitle,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          showValues: settings?.showValues,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          showLabels: settings?.showLabels,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          labelOrder: settings?.labelOrder,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          maxBarThickness: settings?.maxBarThickness,
          ariaLabel: settings?.ariaLabel,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          detailsOnClick: settings?.detailsOnClick,
          barAxisTitle: settings?.barAxisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'stackedBarChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          truncateBy: settings?.truncateBy,
          colorDomain:
            settings?.colorDomain ||
            (getValues(
              'size',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          colorLegendTitle: settings?.colorLegendTitle,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          labelOrder: settings?.labelOrder,
          showValues: settings?.showValues,
          showLabels: settings?.showLabels,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          maxBarThickness: settings?.maxBarThickness,
          minBarThickness: settings?.minBarThickness,
          maxNumberOfBars: settings?.maxNumberOfBars,
          sortParameter: settings?.sortParameter,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          barAxisTitle: settings?.barAxisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedBarChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string | string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          height: settings?.height,
          width: settings?.width,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showValues: settings?.showValues,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          truncateBy: settings?.truncateBy,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          showLabels: settings?.showLabels,
          showColorScale: settings?.showColorScale,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          highlightedDataPoints: settings?.highlightedDataPoints,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          sortData: settings?.sortData,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          autoPlay: settings?.autoPlay,
          autoSort: settings?.autoSort,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          maxBarThickness: settings?.maxBarThickness,
          minBarThickness: settings?.minBarThickness,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          barAxisTitle: settings?.barAxisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedGroupedBarChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showTicks: settings?.showTicks,
          truncateBy: settings?.truncateBy,
          colorDomain:
            settings?.colorDomain ||
            (getValues(
              'size',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          colorLegendTitle: settings?.colorLegendTitle,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          showValues: settings?.showValues,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          showLabels: settings?.showLabels,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          maxBarThickness: settings?.maxBarThickness,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          barAxisTitle: settings?.barAxisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedStackedBarChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          truncateBy: settings?.truncateBy,
          colorDomain:
            settings?.colorDomain ||
            (getValues(
              'size',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          colorLegendTitle: settings?.colorLegendTitle,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          showValues: settings?.showValues,
          showLabels: settings?.showLabels,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          maxBarThickness: settings?.maxBarThickness,
          minBarThickness: settings?.minBarThickness,
          sortParameter: settings?.sortParameter,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          barAxisTitle: settings?.barAxisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'lineChart':
        return {
          theme: settings?.theme,
          curveType: settings?.curveType,
          data: graphData,
          graphID: settings?.graphID,
          lineColor: settings?.lineColor as string | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          noOfXTicks: settings?.noOfXTicks,
          dateFormat: settings?.dateFormat,
          showValues: settings?.showValues,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsDataType[]
            | undefined,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          animateLine: settings?.animateLine,
          strokeWidth: settings?.strokeWidth,
          showDots: settings?.showDots,
          customHighlightAreaSettings: settings?.customHighlightAreaSettings,
          annotations: settings?.annotations,
          regressionLine: settings?.regressionLine,
          ariaLabel: settings?.ariaLabel,
          yAxisTitle: settings?.yAxisTitle,
          noOfYTicks: settings?.noOfYTicks,
          minDate: settings?.minDate,
          maxDate: settings?.maxDate,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'lineChartWithConfidenceInterval':
        return {
          theme: settings?.theme,
          data: graphData,
          curveType: settings?.curveType,
          graphID: settings?.graphID,
          lineColor: settings?.lineColor,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          noOfXTicks: settings?.noOfXTicks,
          dateFormat: settings?.dateFormat,
          showValues: settings?.showValues,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsDataType[]
            | undefined,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          animateLine: settings?.animateLine,
          strokeWidth: settings?.strokeWidth,
          showDots: settings?.showDots,
          customHighlightAreaSettings: settings?.customHighlightAreaSettings,
          annotations: settings?.annotations,
          regressionLine: settings?.regressionLine,
          ariaLabel: settings?.ariaLabel,
          showIntervalDots: settings?.showIntervalDots,
          showIntervalValues: settings?.showIntervalValues,
          intervalLineStrokeWidth: settings?.intervalLineStrokeWidth,
          intervalLineColors: settings?.intervalLineColors,
          intervalAreaColor: settings?.intervalAreaColor,
          intervalAreaOpacity: settings?.intervalAreaOpacity,
          yAxisTitle: settings?.yAxisTitle,
          noOfYTicks: settings?.noOfYTicks,
          minDate: settings?.minDate,
          maxDate: settings?.maxDate,
          colorLegendTitle: settings?.colorLegendTitle,
          colorLegendColors: settings?.colorLegendColors,
          colorLegendDomain: settings?.colorLegendDomain,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'dualAxisLineChart':
        return {
          theme: settings?.theme,
          data: graphData,
          curveType: settings?.curveType,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          labels: settings?.labels || [
            getValues('y1', graphDataConfiguration || [], readableHeader || []),
            getValues('y2', graphDataConfiguration || [], readableHeader || []),
          ],
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          noOfXTicks: settings?.noOfXTicks,
          dateFormat: settings?.dateFormat,
          showValues: settings?.showValues,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          lineColors: settings?.lineColors,
          sameAxes: settings?.sameAxes,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsDataType[]
            | undefined,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          animateLine: settings?.animateLine,
          strokeWidth: settings?.strokeWidth,
          showDots: settings?.showDots,
          colorLegendTitle: settings?.colorLegendTitle,
          ariaLabel: settings?.ariaLabel,
          noOfYTicks: settings?.noOfYTicks,
          minDate: settings?.minDate,
          maxDate: settings?.maxDate,
          lineSuffixes: settings?.lineSuffixes,
          linePrefixes: settings?.linePrefixes,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'multiLineChart':
        return {
          theme: settings?.theme,
          data: graphData,
          curveType: settings?.curveType,
          lineColors: settings?.lineColors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          noOfXTicks: settings?.noOfXTicks,
          dateFormat: settings?.dateFormat,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          labels:
            settings?.labels ||
            (getValues(
              'y',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          showValues: settings?.showValues,
          relativeHeight: settings?.relativeHeight,
          showColorLegendAtTop: settings?.showColorLegendAtTop,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsDataType[]
            | undefined,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          highlightedLines: settings?.highlightedLines,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          animateLine: settings?.animateLine,
          strokeWidth: settings?.strokeWidth,
          showDots: settings?.showDots,
          colorLegendTitle: settings?.colorLegendTitle,
          customHighlightAreaSettings: settings?.customHighlightAreaSettings,
          annotations: settings?.annotations,
          ariaLabel: settings?.ariaLabel,
          yAxisTitle: settings?.yAxisTitle,
          noOfYTicks: settings?.noOfYTicks,
          minDate: settings?.minDate,
          maxDate: settings?.maxDate,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'differenceLineChart':
        return {
          theme: settings?.theme,
          data: graphData,
          curveType: settings?.curveType,
          lineColors: settings?.colors as [string, string] | undefined,
          diffAreaColors: settings?.diffAreaColors,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          noOfXTicks: settings?.noOfXTicks,
          dateFormat: settings?.dateFormat,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          labels: settings?.labels || [
            getValues('y1', graphDataConfiguration || [], readableHeader || []),
            getValues('y2', graphDataConfiguration || [], readableHeader || []),
          ],
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          showValues: settings?.showValues,
          relativeHeight: settings?.relativeHeight,
          showColorLegendAtTop: settings?.showColorLegendAtTop,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsDataType[]
            | undefined,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          animateLine: settings?.animateLine,
          strokeWidth: settings?.strokeWidth,
          showDots: settings?.showDots,
          colorLegendTitle: settings?.colorLegendTitle,
          customHighlightAreaSettings: settings?.customHighlightAreaSettings,
          annotations: settings?.annotations,
          ariaLabel: settings?.ariaLabel,
          yAxisTitle: settings?.yAxisTitle,
          noOfYTicks: settings?.noOfYTicks,
          minDate: settings?.minDate,
          maxDate: settings?.maxDate,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'stackedAreaChart':
        return {
          theme: settings?.theme,
          data: graphData,
          curveType: settings?.curveType,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          noOfXTicks: settings?.noOfXTicks,
          dateFormat: settings?.dateFormat,
          colorDomain:
            settings?.colorDomain ||
            (getValues(
              'y',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          colorLegendTitle: settings?.colorLegendTitle,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          relativeHeight: settings?.relativeHeight,
          bottomMargin: settings?.bottomMargin,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsDataType[]
            | undefined,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          showColorScale: settings?.showColorScale,
          language: settings?.language,
          minHeight: settings?.minHeight,
          customHighlightAreaSettings: settings?.customHighlightAreaSettings,
          annotations: settings?.annotations,
          ariaLabel: settings?.ariaLabel,
          yAxisTitle: settings?.yAxisTitle,
          noOfYTicks: settings?.noOfYTicks,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'choroplethMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          graphTitle: settings?.graphTitle,
          mapData: settings?.mapData,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          colorDomain: settings?.colorDomain as string[] | number[],
          colors: settings?.colors as string[] | undefined,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'x',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          categorical: settings?.categorical,
          data: graphData,
          scale: settings?.scale,
          centerPoint: settings?.centerPoint,
          backgroundColor: settings?.backgroundColor,
          mapBorderWidth: settings?.mapBorderWidth,
          mapNoDataColor: settings?.mapNoDataColor,
          mapBorderColor: settings?.mapBorderColor,
          relativeHeight: settings?.relativeHeight,
          padding: settings?.padding,
          isWorldMap: settings?.isWorldMap,
          tooltip: settings?.tooltip,
          showColorScale: settings?.showColorScale,
          zoomScaleExtend: settings?.zoomScaleExtend,
          zoomTranslateExtend: settings?.zoomTranslateExtend,
          graphID: settings?.graphID,
          highlightedIds: settings?.highlightedIds,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          mapProperty: settings?.mapProperty,
          showAntarctica: settings?.showAntarctica,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          onSeriesMouseClick: (el: any) => {
            updateFilters?.(el.id);
          },
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'biVariateChoroplethMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          mapData: settings?.mapData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          xColorLegendTitle:
            Object.keys(settings || {}).indexOf('xColorLegendTitle') !== -1
              ? settings?.xColorLegendTitle
              : getValues(
                'x',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          yColorLegendTitle:
            Object.keys(settings || {}).indexOf('yColorLegendTitle') !== -1
              ? settings?.yColorLegendTitle
              : getValues(
                'y',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          xDomain: settings?.xDomain as [number, number, number, number],
          yDomain: settings?.yDomain as [number, number, number, number],
          colors: settings?.colors as string[][] | undefined,
          scale: settings?.scale,
          centerPoint: settings?.centerPoint,
          backgroundColor: settings?.backgroundColor,
          mapBorderWidth: settings?.mapBorderWidth,
          mapNoDataColor: settings?.mapNoDataColor,
          padding: settings?.padding,
          mapBorderColor: settings?.mapBorderColor,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          isWorldMap: settings?.isWorldMap,
          zoomScaleExtend: settings?.zoomScaleExtend,
          zoomTranslateExtend: settings?.zoomTranslateExtend,
          graphID: settings?.graphID,
          highlightedIds: settings?.highlightedIds,
          mapProperty: settings?.mapProperty,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          showAntarctica: settings?.showAntarctica,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          onSeriesMouseClick: (el: any) => {
            updateFilters?.(el.id);
          },
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'dotDensityMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          graphTitle: settings?.graphTitle,
          mapData: settings?.mapData,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          radius: settings?.radius,
          sources: settings?.sources,
          colors: settings?.colors as string | string[] | undefined,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          data: graphData,
          scale: settings?.scale,
          centerPoint: settings?.centerPoint,
          backgroundColor: settings?.backgroundColor,
          mapBorderWidth: settings?.mapBorderWidth,
          mapNoDataColor: settings?.mapNoDataColor,
          mapBorderColor: settings?.mapBorderColor,
          padding: settings?.padding,
          showLabels: settings?.showLabels,
          relativeHeight: settings?.relativeHeight,
          isWorldMap: settings?.isWorldMap,
          tooltip: settings?.tooltip,
          showColorScale: settings?.showColorScale,
          zoomScaleExtend: settings?.zoomScaleExtend,
          zoomTranslateExtend: settings?.zoomTranslateExtend,
          graphID: settings?.graphID,
          highlightedDataPoints: settings?.highlightedDataPoints,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          showAntarctica: settings?.showAntarctica,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'donutChart':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          mainText: settings?.mainText,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          graphDescription: settings?.graphDescription,
          subNote: settings?.subNote,
          footNote: settings?.footNote,
          radius: settings?.radius,
          strokeWidth: settings?.strokeWidth,
          showColorScale: settings?.showColorScale,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          colorDomain: settings?.colorDomain,
          sortData: settings?.sortData,
          language: settings?.language,
          width: settings?.width,
          height: settings?.height,
          minHeight: settings?.minHeight,
          relativeHeight: settings?.relativeHeight,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          ariaLabel: settings?.ariaLabel,
          legendMaxWidth: settings?.legendMaxWidth,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          onSeriesMouseClick: (el: any) => {
            updateFilters?.(el.label);
          },
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'slopeChart':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          showLabels: settings?.showLabels,
          colors: settings?.colors as string | string[] | undefined,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          radius: settings?.radius,
          axisTitles: settings?.axisTitles,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          highlightedDataPoints: settings?.highlightedDataPoints,
          showColorScale: settings?.showColorScale,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          fillContainer: settings?.fillContainer,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'scatterPlot':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          showLabels: settings?.showLabels,
          colors: settings?.colors as string | string[] | undefined,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          radius: settings?.radius,
          xAxisTitle: 
            Object.keys(settings || {}).indexOf('xAxisTitle') !== -1
              ? settings?.xAxisTitle
              : getValues(
                'x',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          yAxisTitle: 
            Object.keys(settings || {}).indexOf('yAxisTitle') !== -1
              ? settings?.yAxisTitle
              : getValues(
                'y',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refXValues: settings?.refXValues,
          refYValues: settings?.refYValues,
          highlightedDataPoints: settings?.highlightedDataPoints,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsForScatterPlotDataType[]
            | undefined,
          showColorScale: settings?.showColorScale,
          graphID: settings?.graphID,
          maxRadiusValue: settings?.maxRadiusValue,
          maxXValue: settings?.maxXValue,
          minXValue: settings?.minXValue,
          maxYValue: settings?.maxYValue,
          minYValue: settings?.minYValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          customHighlightAreaSettings: settings?.customHighlightAreaSettings,
          annotations: settings?.annotations,
          regressionLine: settings?.regressionLine,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          noOfXTicks: settings?.noOfXTicks,
          noOfYTicks: settings?.noOfYTicks,
          labelColor: settings?.labelColor,
          xSuffix: settings?.xSuffix,
          ySuffix: settings?.ySuffix,
          xPrefix: settings?.xPrefix,
          yPrefix: settings?.yPrefix,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'dumbbellChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          refValues: settings?.refValues,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          truncateBy: settings?.truncateBy,
          labelOrder: settings?.labelOrder,
          colorDomain:
            settings?.colorDomain ||
            (getValues(
              'x',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          colorLegendTitle: settings?.colorLegendTitle,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          radius: settings?.radius,
          relativeHeight: settings?.relativeHeight,
          showValues: settings?.showValues,
          showLabels: settings?.showLabels,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          maxPositionValue: settings?.maxPositionValue,
          minPositionValue: settings?.minPositionValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          language: settings?.language,
          minHeight: settings?.minHeight,
          sortParameter: settings?.sortParameter,
          arrowConnector: settings?.arrowConnector,
          connectorStrokeWidth: settings?.connectorStrokeWidth,
          maxBarThickness: settings?.maxBarThickness,
          minBarThickness: settings?.minBarThickness,
          maxNumberOfBars: settings?.maxNumberOfBars,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          axisTitle: settings?.axisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'treeMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string | string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          showLabels: settings?.showLabels,
          tooltip: settings?.tooltip,
          showColorScale: settings?.showColorScale,
          showValues: settings?.showValues,
          graphID: settings?.graphID,
          highlightedDataPoints: settings?.highlightedDataPoints,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          ariaLabel: settings?.ariaLabel,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          onSeriesMouseClick: (el: any) => {
            updateFilters?.(el.label);
          },
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'circlePacking':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string | string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          showLabels: settings?.showLabels,
          tooltip: settings?.tooltip,
          showColorScale: settings?.showColorScale,
          showValues: settings?.showValues,
          graphID: settings?.graphID,
          highlightedDataPoints: settings?.highlightedDataPoints,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          ariaLabel: settings?.ariaLabel,
          radius: settings?.radius,
          maxRadiusValue: settings?.maxRadiusValue,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          onSeriesMouseClick: (el: any) => {
            updateFilters?.(el.label);
          },
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'heatMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          scaleType: settings?.scaleType,
          colorDomain: settings?.colorDomain as string[] | number[],
          showColumnLabels: settings?.showColumnLabels,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          truncateBy: settings?.truncateBy,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          showValues: settings?.showValues,
          showRowLabels: settings?.showRowLabels,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          noDataColor: settings?.noDataColor,
          showColorScale: settings?.showColorScale,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          fillContainer: settings?.fillContainer,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'stripChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          colors: settings?.colors as string | string[] | undefined,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          radius: settings?.radius,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          highlightedDataPoints: settings?.highlightedDataPoints,
          showColorScale: settings?.showColorScale,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          showAxis: settings?.showAxis,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          prefix: settings?.prefix,
          suffix: settings?.suffix,
          stripType: settings?.stripType,
          valueColor: settings?.valueColor,
          language: settings?.language,
          minHeight: settings?.minHeight,
          highlightColor: settings?.highlightColor,
          dotOpacity: settings?.dotOpacity,
          showNAColor: settings?.showNAColor,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'beeSwarmChart':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string | string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          showLabels: settings?.showLabels,
          showColorScale: settings?.showColorScale,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          radius: settings?.radius,
          maxRadiusValue: settings?.maxRadiusValue,
          maxPositionValue: settings?.maxPositionValue,
          minPositionValue: settings?.minPositionValue,
          highlightedDataPoints: settings?.highlightedDataPoints,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          orientation: settings?.orientation,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'butterflyChart':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          leftBarTitle:
            Object.keys(settings || {}).indexOf('leftBarTitle') !== -1
              ? settings?.leftBarTitle
              : getValues(
                'leftBar',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          rightBarTitle:
            Object.keys(settings || {}).indexOf('rightBarTitle') !== -1
              ? settings?.rightBarTitle
              : getValues(
                'rightBar',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          barColors: settings?.barColors,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          barPadding: settings?.barPadding,
          truncateBy: settings?.truncateBy,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          showTicks: settings?.showTicks,
          showValues: settings?.showValues,
          centerGap: settings?.centerGap,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          showColorScale: settings?.showColorScale,
          refValues: settings?.refValues,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'histogram':
        return {
          theme: settings?.theme,
          data: graphData,
          colors: settings?.colors,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showValues: settings?.showValues,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          showLabels: settings?.showLabels,
          maxValue: settings?.maxValue,
          tooltip: settings?.tooltip,
          refValues: settings?.refValues,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          numberOfBins: settings?.numberOfBins,
          truncateBy: settings?.truncateBy,
          donutStrokeWidth: settings?.donutStrokeWidth,
          sortData: settings?.sortData,
          barGraphLayout: settings?.barGraphLayout,
          graphType: settings?.graphType,
          language: settings?.language,
          minHeight: settings?.minHeight,
          maxBarThickness: settings?.maxBarThickness,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'sparkLine':
        return {
          theme: settings?.theme,
          data: graphData,
          curveType: settings?.curveType,
          lineColor: settings?.lineColor as string | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          dateFormat: settings?.dateFormat,
          area: settings?.area,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'paretoChart':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          showValues: settings?.showValues,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          barTitle:
            Object.keys(settings || {}).indexOf('barTitle') !== -1
              ? settings?.barTitle
              : getValues(
                'barTitle',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          lineTitle:
            Object.keys(settings || {}).indexOf('lineTitle') !== -1
              ? settings?.lineTitle
              : getValues(
                'lineTitle',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          barColor: settings?.barColor,
          curveType: settings?.curveType,
          lineColor: settings?.lineColor,
          sameAxes: settings?.sameAxes,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          barPadding: settings?.barPadding,
          truncateBy: settings?.truncateBy,
          showLabels: settings?.showLabels,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          noOfTicks: settings?.noOfTicks,
          lineSuffix: settings?.lineSuffix,
          barSuffix: settings?.barSuffix,
          linePrefix: settings?.lineSuffix,
          barPrefix: settings?.barPrefix,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'dataTable':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          graphTitle: settings?.graphTitle,
          sources: settings?.sources,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          graphID: settings?.graphID,
          width: settings?.width,
          height: settings?.height,
          columnData: (settings?.columnData || []) as DataTableColumnDataType[],
          data: graphData,
          language: settings?.language,
          ariaLabel: settings?.ariaLabel,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'statCard':
        return {
          theme: settings?.theme,
          year: settings?.year,
          data: graphData,
          graphTitle: settings?.graphTitle || '',
          graphDescription: settings?.graphDescription,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          sources: settings?.sources || [],
          footNote: settings?.footNote,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          graphID: settings?.graphID,
          aggregationMethod: settings?.aggregationMethod,
          language: settings?.language,
          minHeight: settings?.minHeight,
          countOnly: settings?.countOnly,
          ariaLabel: settings?.ariaLabel,
          textBackground: settings?.textBackground,
          headingFontSize: settings?.headingFontSize,
          centerAlign: settings?.centerAlign,
          verticalAlign: settings?.verticalAlign,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'geoHubCompareMap':
        return {
          theme: settings?.theme,
          graphTitle: settings?.graphTitle,
          sources: settings?.sources,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          width: settings?.width,
          height: settings?.height,
          relativeHeight: settings?.relativeHeight,
          graphID: settings?.graphID,
          mapStyles: settings?.mapStyles as [string, string],
          center: settings?.center,
          zoomLevel: settings?.zoomLevel,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'geoHubMap':
        return {
          theme: settings?.theme,
          mapStyle: settings?.mapStyle,
          center: settings?.center,
          zoomLevel: settings?.zoomLevel,
          graphTitle: settings?.graphTitle,
          sources: settings?.sources,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          width: settings?.width,
          height: settings?.height,
          relativeHeight: settings?.relativeHeight,
          graphID: settings?.graphID,
          language: settings?.language,
          minHeight: settings?.minHeight,
          includeLayers: settings?.includeLayers,
          excludeLayers: settings?.excludeLayers,
          ariaLabel: settings?.ariaLabel,
          uiMode: settings?.uiMode,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'geoHubMapWithLayerSelection':
        return {
          theme: settings?.theme,
          mapStyle: settings?.mapStyle,
          center: settings?.center,
          zoomLevel: settings?.zoomLevel,
          graphTitle: settings?.graphTitle,
          sources: settings?.sources,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          width: settings?.width,
          height: settings?.height,
          relativeHeight: settings?.relativeHeight,
          graphID: settings?.graphID,
          language: settings?.language,
          minHeight: settings?.minHeight,
          layerSelection: settings?.layerSelection,
          excludeLayers: settings?.excludeLayers,
          ariaLabel: settings?.ariaLabel,
          uiMode: settings?.uiMode,
        };
      case 'unitChart':
        return {
          theme: settings?.theme,
          totalNoOfDots: settings?.totalNoOfDots,
          gridSize: settings?.gridSize,
          unitPadding: settings?.unitPadding,
          size: settings?.size,
          graphTitle: settings?.graphTitle,
          sources: settings?.sources,
          colors: settings?.colors as string[] | undefined,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          showColorScale: settings?.showColorScale,
          showStrokeForWhiteDots: settings?.showStrokeForWhiteDots,
          note: settings?.note,
          data: graphData,
          width: settings?.width,
          height: settings?.height,
          minHeight: settings?.minHeight,
          relativeHeight: settings?.relativeHeight,
          ariaLabel: settings?.ariaLabel,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedBiVariateChoroplethMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          mapData: settings?.mapData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          xColorLegendTitle:
            Object.keys(settings || {}).indexOf('xColorLegendTitle') !== -1
              ? settings?.xColorLegendTitle
              : getValues(
                'x',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          yColorLegendTitle:
            Object.keys(settings || {}).indexOf('yColorLegendTitle') !== -1
              ? settings?.yColorLegendTitle
              : getValues(
                'y',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          xDomain: settings?.xDomain as [number, number, number, number],
          yDomain: settings?.yDomain as [number, number, number, number],
          colors: settings?.colors as string[][] | undefined,
          scale: settings?.scale,
          centerPoint: settings?.centerPoint,
          backgroundColor: settings?.backgroundColor,
          mapBorderWidth: settings?.mapBorderWidth,
          mapNoDataColor: settings?.mapNoDataColor,
          padding: settings?.padding,
          mapBorderColor: settings?.mapBorderColor,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          isWorldMap: settings?.isWorldMap,
          zoomScaleExtend: settings?.zoomScaleExtend,
          zoomTranslateExtend: settings?.zoomTranslateExtend,
          graphID: settings?.graphID,
          highlightedIds: settings?.highlightedIds,
          mapProperty: settings?.mapProperty,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          showAntarctica: settings?.showAntarctica,
          language: settings?.language,
          minHeight: settings?.minHeight,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedChoroplethMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          graphTitle: settings?.graphTitle,
          mapData: settings?.mapData,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          colorDomain: settings?.colorDomain as string[] | number[],
          colors: settings?.colors as string[] | undefined,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'x',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          categorical: settings?.categorical,
          data: graphData,
          scale: settings?.scale,
          centerPoint: settings?.centerPoint,
          backgroundColor: settings?.backgroundColor,
          mapBorderWidth: settings?.mapBorderWidth,
          mapNoDataColor: settings?.mapNoDataColor,
          mapBorderColor: settings?.mapBorderColor,
          relativeHeight: settings?.relativeHeight,
          padding: settings?.padding,
          isWorldMap: settings?.isWorldMap,
          tooltip: settings?.tooltip,
          showColorScale: settings?.showColorScale,
          zoomScaleExtend: settings?.zoomScaleExtend,
          zoomTranslateExtend: settings?.zoomTranslateExtend,
          graphID: settings?.graphID,
          highlightedIds: settings?.highlightedIds,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          mapProperty: settings?.mapProperty,
          showAntarctica: settings?.showAntarctica,
          language: settings?.language,
          minHeight: settings?.minHeight,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedDotDensityMap':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          graphTitle: settings?.graphTitle,
          mapData: settings?.mapData,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          radius: settings?.radius,
          sources: settings?.sources,
          colors: settings?.colors as string | string[] | undefined,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          data: graphData,
          scale: settings?.scale,
          centerPoint: settings?.centerPoint,
          backgroundColor: settings?.backgroundColor,
          mapBorderWidth: settings?.mapBorderWidth,
          mapNoDataColor: settings?.mapNoDataColor,
          mapBorderColor: settings?.mapBorderColor,
          padding: settings?.padding,
          showLabels: settings?.showLabels,
          relativeHeight: settings?.relativeHeight,
          isWorldMap: settings?.isWorldMap,
          tooltip: settings?.tooltip,
          showColorScale: settings?.showColorScale,
          zoomScaleExtend: settings?.zoomScaleExtend,
          zoomTranslateExtend: settings?.zoomTranslateExtend,
          graphID: settings?.graphID,
          highlightedDataPoints: settings?.highlightedDataPoints,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          showAntarctica: settings?.showAntarctica,
          language: settings?.language,
          minHeight: settings?.minHeight,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedButterflyChart':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          leftBarTitle:
            Object.keys(settings || {}).indexOf('leftBarTitle') !== -1
              ? settings?.leftBarTitle
              : getValues(
                'leftBar',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          rightBarTitle:
            Object.keys(settings || {}).indexOf('rightBarTitle') !== -1
              ? settings?.rightBarTitle
              : getValues(
                'rightBar',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          barColors: settings?.barColors,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          barPadding: settings?.barPadding,
          truncateBy: settings?.truncateBy,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          showTicks: settings?.showTicks,
          showValues: settings?.showValues,
          centerGap: settings?.centerGap,
          maxValue: settings?.maxValue,
          minValue: settings?.minValue,
          showColorScale: settings?.showColorScale,
          refValues: settings?.refValues,
          language: settings?.language,
          minHeight: settings?.minHeight,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedDumbbellChart':
        return {
          theme: settings?.theme,
          orientation: settings?.orientation,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          colors: settings?.colors as string[] | undefined,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          refValues: settings?.refValues,
          sources: settings?.sources,
          barPadding: settings?.barPadding,
          showTicks: settings?.showTicks,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          truncateBy: settings?.truncateBy,
          colorDomain:
            settings?.colorDomain ||
            (getValues(
              'x',
              graphDataConfiguration || [],
              readableHeader || [],
            ) as string[]),
          colorLegendTitle: settings?.colorLegendTitle,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          radius: settings?.radius,
          relativeHeight: settings?.relativeHeight,
          showValues: settings?.showValues,
          showLabels: settings?.showLabels,
          tooltip: settings?.tooltip,
          graphID: settings?.graphID,
          maxPositionValue: settings?.maxPositionValue,
          minPositionValue: settings?.minPositionValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          language: settings?.language,
          minHeight: settings?.minHeight,
          sortParameter: settings?.sortParameter,
          arrowConnector: settings?.arrowConnector,
          connectorStrokeWidth: settings?.connectorStrokeWidth,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          maxBarThickness: settings?.maxBarThickness,
          minBarThickness: settings?.minBarThickness,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          axisTitle: settings?.axisTitle,
          noOfTicks: settings?.noOfTicks,
          valueColor: settings?.valueColor,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'animatedScatterPlot':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          showLabels: settings?.showLabels,
          colors: settings?.colors as string | string[] | undefined,
          colorDomain: settings?.colorDomain,
          colorLegendTitle:
            Object.keys(settings || {}).indexOf('colorLegendTitle') !== -1
              ? settings?.colorLegendTitle
              : getValues(
                'color',
                graphDataConfiguration || [],
                readableHeader || [],
              ),
          radius: settings?.radius,
          xAxisTitle: settings?.xAxisTitle,
          yAxisTitle: settings?.yAxisTitle,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          relativeHeight: settings?.relativeHeight,
          tooltip: settings?.tooltip,
          refXValues: settings?.refXValues,
          refYValues: settings?.refYValues,
          highlightedDataPoints: settings?.highlightedDataPoints,
          highlightAreaSettings: settings?.highlightAreaSettings as
            | HighlightAreaSettingsForScatterPlotDataType[]
            | undefined,
          showColorScale: settings?.showColorScale,
          graphID: settings?.graphID,
          maxRadiusValue: settings?.maxRadiusValue,
          maxXValue: settings?.maxXValue,
          minXValue: settings?.minXValue,
          maxYValue: settings?.maxYValue,
          minYValue: settings?.minYValue,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          language: settings?.language,
          minHeight: settings?.minHeight,
          showNAColor: settings?.showNAColor,
          autoPlay: settings?.autoPlay,
          showOnlyActiveDate: settings?.showOnlyActiveDate,
          dateFormat: settings?.dateFormat,
          customHighlightAreaSettings: settings?.customHighlightAreaSettings,
          annotations: settings?.annotations,
          ariaLabel: settings?.ariaLabel,
          detailsOnClick: settings?.detailsOnClick,
          noOfXTicks: settings?.noOfXTicks,
          noOfYTicks: settings?.noOfYTicks,
          labelColor: settings?.labelColor,
          xSuffix: settings?.xSuffix,
          ySuffix: settings?.ySuffix,
          xPrefix: settings?.xPrefix,
          yPrefix: settings?.yPrefix,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'sankeyChart':
        return {
          theme: settings?.theme,
          resetSelectionOnDoubleClick: settings?.resetSelectionOnDoubleClick,
          data: graphData,
          graphTitle: settings?.graphTitle,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          width: settings?.width,
          height: settings?.height,
          sources: settings?.sources,
          showLabels: settings?.showLabels,
          leftMargin: settings?.leftMargin,
          rightMargin: settings?.rightMargin,
          topMargin: settings?.topMargin,
          bottomMargin: settings?.bottomMargin,
          truncateBy: settings?.truncateBy,
          padding: settings?.padding,
          backgroundColor: settings?.backgroundColor,
          tooltip: settings?.tooltip,
          suffix: settings?.suffix,
          prefix: settings?.prefix,
          relativeHeight: settings?.relativeHeight,
          showValues: settings?.showValues,
          graphID: settings?.graphID,
          graphDownload: settings?.graphDownload,
          dataDownload: settings?.dataDownload,
          fillContainer: settings?.fillContainer,
          language: settings?.language,
          minHeight: settings?.minHeight,
          ariaLabel: settings?.ariaLabel,
          sourceColors: settings?.sourceColors,
          targetColors: settings?.targetColors,
          sourceColorDomain: settings?.sourceColorDomain,
          targetColorDomain: settings?.targetColorDomain,
          nodePadding: settings?.nodePadding,
          nodeWidth: settings?.nodeWidth,
          highlightedSourceDataPoints: settings?.highlightedSourceDataPoints,
          highlightedTargetDataPoints: settings?.highlightedTargetDataPoints,
          defaultLinkOpacity: settings?.defaultLinkOpacity,
          sourceTitle: settings?.sourceTitle,
          targetTitle: settings?.targetTitle,
          animateLinks: settings?.animateLinks,
          sortNodes: settings?.sortNodes,
          detailsOnClick: settings?.detailsOnClick,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      case 'dataCards':
        return {
          theme: settings?.theme,
          graphTitle: settings?.graphTitle,
          sources: settings?.sources,
          graphDescription: settings?.graphDescription,
          footNote: settings?.footNote,
          graphID: settings?.graphID,
          width: settings?.width,
          height: settings?.height,
          columnData: (settings?.columnData || []) as DataTableColumnDataType[],
          data: graphData,
          language: settings?.language,
          ariaLabel: settings?.ariaLabel,
          cardTemplate: settings?.cardTemplate,
          cardBackgroundColor: settings?.cardBackgroundColor,
          cardFilters: settings?.cardFilters || [],
          cardSortingOptions: settings?.cardSortingOptions,
          cardSearchColumns: settings?.cardSearchColumns,
          cardMinWidth: settings?.cardMinWidth,
          backgroundColor: settings?.backgroundColor,
          padding: settings?.padding,
          detailsOnClick: settings?.detailsOnClick,
          allowDataDownloadOnDetail: settings?.allowDataDownloadOnDetail,
          noOfItemsInAPage: settings?.noOfItemsInAPage,
          uiMode: settings?.uiMode,
          styles: settings?.styles,
          classNames: settings?.classNames,
        };
      default:
        return {};
    }
  };
  const GraphComponent = graphComponents[graph];
  const graphProps = getGraphProps(graph);
  return (
    <div
      className={`grow my-0 ${
        graph !== 'statCard' ? 'mx-auto' : 'mx-0'
      } flex flex-col h-inherit ${settings?.width ? 'w-fit' : 'w-full'} ${
        graph !== 'unitChart' && graph !== 'statCard'
          ? 'justify-center'
          : 'justify-start'
      } ${settings?.theme || 'light'}`}
      style={{ minHeight: 'inherit' }}
    >
      {validateSettingsSchema(getGraphProps(graph) || {}, graph).isValid &&
      validateDataSchema(graphData, graph).isValid &&
      GraphComponent ? (
         
        <GraphComponent {...graphProps} />
        ) : (
          <P
            size='sm'
            marginBottom='none'
            className='p-2 text-center text-accent-dark-red dark:text-accent-red'
          >
            {GraphComponent
              ? validateSettingsSchema(settings || {}, graph).isValid
                ? `Error in data: ${validateDataSchema(graphData, graph).err}`
                : `Error in settings: ${
                  validateSettingsSchema(settings || {}, graph).err
                }`
              : `Invalid chart type: ${graph}`}
          </P>
        )}
    </div>
  );
}

export default GraphEl;
